"use client";
import { useEffect, useMemo, useState } from "react";
import type { Deal } from "@/lib/deal-types";

const blank: Partial<Deal> = { title:"", platform:"Amazon", category:"Electronics", price:0, mrp:0, url:"", imageUrl:"", tag:"New deal", code:"", couponTerms:"", expires:"Limited time", expiryDate:"", emoji:"DEAL", color:"#e7f1ec", active:true, status:"published", rating:4.5, votes:0, source:"manual" };
const sampleCsv = "title,platform,category,price,mrp,url,imageUrl,tag,code,couponTerms,expires,expiryDate,rating,votes\nProduct name,Amazon,Electronics,1499,2999,https://www.amazon.in/example,https://example.com/image.jpg,Hot deal,SAVE10,Selected users,Ends tonight,2026-08-01,4.5,100";

export default function AdminDashboard() {
  const [deals,setDeals] = useState<Deal[]>([]);
  const [form,setForm] = useState<Partial<Deal>>(blank);
  const [message,setMessage] = useState("Loading catalogue...");
  const [amazon,setAmazon] = useState<{ready:boolean;missing:string[]}|null>(null);
  const [filter,setFilter] = useState("all");
  const [csv,setCsv] = useState("");
  const [amazonCount,setAmazonCount] = useState(50);
  const [amazonSaving,setAmazonSaving] = useState(20);
  const [amazonCsv,setAmazonCsv] = useState("");
  const [amazonItems,setAmazonItems] = useState<Array<{title:string;price:number;mrp:number;imageUrl:string;category:string}>>([]);
  const [amazonBusy,setAmazonBusy] = useState(false);
  const [xlsxFile,setXlsxFile] = useState<File|null>(null);
  const [xlsxBusy,setXlsxBusy] = useState(false);
  const [xlsxResult,setXlsxResult] = useState<{valid:boolean;hash:string;rowCount:number;errors:string[];warnings:string[];rows:Array<Record<string,string>>}|null>(null);
  const today = new Date().toISOString().slice(0,10);
  const stats = useMemo(() => ({published:deals.filter(d=>d.status==="published"&&d.active).length,review:deals.filter(d=>d.status==="review").length,expired:deals.filter(d=>d.status==="expired").length,today:deals.filter(d=>d.status==="published"&&d.updatedAt?.startsWith(today)).length}),[deals,today]);
  const visible = deals.filter(d=>filter==="all"||d.status===filter);
  const load = async () => { const response=await fetch("/api/admin/deals",{cache:"no-store"}); if(!response.ok)return setMessage("Sign-in failed."); setDeals(await response.json()); setMessage(""); };
  useEffect(()=>{load();fetch("/api/admin/amazon").then(r=>r.json()).then(setAmazon).catch(()=>null)},[]);
  const update=(key:keyof Deal,value:string|number|boolean)=>setForm(current=>({...current,[key]:value}));
  const save=async(event:React.FormEvent)=>{event.preventDefault();setMessage("Saving...");const response=await fetch("/api/admin/deals",{method:form.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});if(!response.ok)return setMessage((await response.json()).error||"Could not save.");setForm(blank);setMessage("Deal saved.");await load()};
  const setStatus=async(deal:Deal,status:Deal["status"])=>{await fetch("/api/admin/deals",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...deal,status,active:status==="published"})});await load()};
  const remove=async(id:number)=>{if(!confirm("Delete this deal permanently?"))return;await fetch(`/api/admin/deals?id=${id}`,{method:"DELETE"});await load()};
  const importCsv=async()=>{if(!csv.trim())return setMessage("Paste CSV data first.");setMessage("Importing and checking duplicates...");const response=await fetch("/api/admin/import",{method:"POST",headers:{"Content-Type":"text/csv"},body:csv});const result=await response.json();if(!response.ok)return setMessage(result.error||"Import failed.");setCsv("");setMessage(`${result.imported} imported for review · ${result.skipped} duplicates skipped · ${result.errors.length} errors`);await load()};
  const readFile=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>setCsv(String(reader.result||""));reader.readAsText(file)};
  const generateAmazon=async()=>{setAmazonBusy(true);setMessage("Requesting discounted products from Amazon...");const response=await fetch("/api/admin/amazon",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({count:amazonCount,minSavingPercent:amazonSaving})});const result=await response.json();setAmazonBusy(false);if(!response.ok)return setMessage(result.error||"Amazon generation failed.");setAmazonCsv(result.csv);setAmazonItems(result.items);setMessage(`${result.items.length} Amazon deals generated. Review, download or send them to the import queue.`)};
  const downloadAmazon=()=>{const blob=new Blob([amazonCsv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`amazon-top-deals-${today}.csv`;link.click();URL.revokeObjectURL(url)};
  const queueAmazon=()=>{setCsv(amazonCsv);setMessage("Amazon CSV copied to the bulk importer. Review it and click Import to review queue.")};
  const chooseXlsx=(file?:File)=>{setXlsxFile(file||null);setXlsxResult(null);setMessage(file?`${file.name} selected. Validate it before publishing.`:"")};
  const validateWorkbook=async()=>{if(!xlsxFile)return setMessage("Choose an Excel workbook first.");setXlsxBusy(true);const body=new FormData();body.set("file",xlsxFile);body.set("action","validate");const response=await fetch("/api/admin/import-xlsx",{method:"POST",body});const result=await response.json();setXlsxBusy(false);if(!response.ok){setXlsxResult(null);return setMessage(result.error||"Validation failed.");}setXlsxResult(result);setMessage(result.valid?`${result.rowCount} rows are valid and ready to publish.`:`Validation found ${result.errors.length} issue(s). Fix the workbook and upload it again.`)};
  const publishWorkbook=async()=>{if(!xlsxFile||!xlsxResult?.valid)return;setXlsxBusy(true);const body=new FormData();body.set("file",xlsxFile);body.set("action","publish");body.set("hash",xlsxResult.hash);const response=await fetch("/api/admin/import-xlsx",{method:"POST",body});const result=await response.json();setXlsxBusy(false);if(!response.ok)return setMessage(result.error||"Import failed.");setMessage(`${result.published} deals published · ${result.skipped} existing deals skipped.`);setXlsxFile(null);setXlsxResult(null);await load()};

  return <main className="admin-shell">
    <header className="admin-header"><div><a className="brand" href="/"><span className="brand-mark">%</span><span>deals<span className="brand-dot">.</span></span></a><p>Automation control room</p></div><div className="admin-user"><span>Admin</span><strong>tech@ads-ai.in</strong></div></header>
    <section className="admin-hero ops-hero"><div><span className="eyebrow dark">DAILY DEAL OPERATIONS</span><h1>100 smart deals.<br/>Every day.</h1><p>Import, review, publish and expire offers from one place.</p></div><div className="daily-goal"><div className="goal-ring" style={{"--progress":`${Math.min(stats.today,100)*3.6}deg`} as React.CSSProperties}><b>{stats.today}</b><span>/ 100 today</span></div></div><div className="admin-stats"><article><b>{stats.published}</b><span>Live now</span></article><article><b>{stats.review}</b><span>Needs review</span></article><article><b>{stats.expired}</b><span>Expired</span></article></div></section>
    <section className="amazon-generator"><div className="amazon-generator-head"><div className="amazon-badge">amazon</div><div><h2>Amazon Top Deals → CSV</h2><p>{amazon?.ready?"Secure Creators API connection is ready. Generate up to 50 discounted products.":"Generator is installed. It activates after Creators API credentials are added to the VPS."}</p></div><span className={amazon?.ready?"status ready":"status"}>{amazon?.ready?"Ready":"Credentials required"}</span></div>
      <div className="amazon-controls"><label>Number of deals<select value={amazonCount} onChange={e=>setAmazonCount(Number(e.target.value))}><option>10</option><option>20</option><option>30</option><option>40</option><option>50</option></select></label><label>Minimum saving<select value={amazonSaving} onChange={e=>setAmazonSaving(Number(e.target.value))}><option value="10">10%+</option><option value="20">20%+</option><option value="30">30%+</option><option value="40">40%+</option><option value="50">50%+</option></select></label><button className="admin-primary" disabled={!amazon?.ready||amazonBusy} onClick={generateAmazon}>{amazonBusy?"Fetching Amazon…":"Generate Top Deals CSV"}</button></div>
      {amazonItems.length>0&&<><div className="amazon-preview">{amazonItems.slice(0,5).map((item,index)=><article key={`${item.title}-${index}`}>{item.imageUrl?<img src={item.imageUrl} alt=""/>:<span>DEAL</span>}<div><small>{item.category}</small><h3>{item.title}</h3><p>₹{item.price.toLocaleString("en-IN")} <s>₹{item.mrp.toLocaleString("en-IN")}</s></p></div></article>)}</div><div className="amazon-output"><span>Previewing 5 of {amazonItems.length} generated deals</span><button onClick={downloadAmazon}>Download CSV</button><button className="admin-primary" onClick={queueAmazon}>Send to bulk importer</button></div></>}
    </section>
    <section className="xlsx-importer"><div className="xlsx-title"><span className="import-icon">XLSX</span><div><h2>Excel deal publisher</h2><p>Download the template, upload your completed workbook, validate every row, then publish.</p></div></div><div className="xlsx-steps"><article className="active"><b>1</b><div><strong>Prepare workbook</strong><span>Use our formatted sample</span></div></article><i/><article className={xlsxFile?"active":""}><b>2</b><div><strong>Validate file</strong><span>Check structure and values</span></div></article><i/><article className={xlsxResult?.valid?"active":""}><b>3</b><div><strong>Import & publish</strong><span>Add valid deals to the site</span></div></article></div>
      <div className="xlsx-actions"><a className="template-download" href="/downloads/deals-import-template.xlsx" download>Download sample XLSX</a><label className="xlsx-picker"><input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>chooseXlsx(e.target.files?.[0])}/><span>{xlsxFile?xlsxFile.name:"Choose completed XLSX"}</span></label><button onClick={validateWorkbook} disabled={!xlsxFile||xlsxBusy}>{xlsxBusy?"Checking…":"Validate workbook"}</button><button className="publish-xlsx" onClick={publishWorkbook} disabled={!xlsxResult?.valid||xlsxBusy}>Import & publish</button></div>
      {xlsxResult&&<div className={xlsxResult.valid?"validation-panel valid":"validation-panel invalid"}><div><b>{xlsxResult.valid?"✓ Workbook is valid":"! Workbook needs attention"}</b><span>{xlsxResult.rowCount} data rows · {xlsxResult.errors.length} errors · {xlsxResult.warnings.length} warnings</span></div>{xlsxResult.errors.length>0&&<ul>{xlsxResult.errors.slice(0,8).map(error=><li key={error}>{error}</li>)}</ul>}{xlsxResult.warnings.length>0&&<ul className="warnings">{xlsxResult.warnings.map(warning=><li key={warning}>{warning}</li>)}</ul>}{xlsxResult.valid&&<div className="xlsx-preview"><div className="xlsx-preview-head"><span>Title</span><span>Store</span><span>Price</span><span>MRP</span></div>{xlsxResult.rows.slice(0,5).map((row,index)=><div key={`${row.title}-${index}`}><span>{row.title}</span><span>{row.platform}</span><span>₹{Number(row.price).toLocaleString("en-IN")}</span><span>₹{Number(row.mrp).toLocaleString("en-IN")}</span></div>)}</div>}</div>}
      <details className="legacy-csv"><summary>Need the legacy CSV importer?</summary><input type="file" accept=".csv,text/csv" onChange={e=>readFile(e.target.files?.[0])}/><textarea value={csv} onChange={e=>setCsv(e.target.value)} placeholder={sampleCsv}/><div className="import-actions"><button onClick={()=>setCsv(sampleCsv)}>Load CSV template</button><button className="admin-primary" onClick={importCsv}>Import to review queue</button></div></details>
    </section>
    <div className="admin-grid"><form className="deal-form" onSubmit={save}><div className="form-title"><h2>{form.id?"Edit deal":"Add one deal"}</h2>{form.id&&<button type="button" onClick={()=>setForm(blank)}>Cancel</button>}</div>
      <label>Deal title<input required value={form.title||""} onChange={e=>update("title",e.target.value)}/></label><div className="form-row"><label>Store<input required value={form.platform||""} onChange={e=>update("platform",e.target.value)}/></label><label>Category<select value={form.category} onChange={e=>update("category",e.target.value)}>{["Mobiles","Electronics","Fashion","Home","Beauty","Travel","Food","Finance"].map(x=><option key={x}>{x}</option>)}</select></label></div>
      <div className="form-row"><label>Deal price (₹)<input required min="0" type="number" value={form.price||""} onChange={e=>update("price",Number(e.target.value))}/></label><label>MRP (₹)<input required min="1" type="number" value={form.mrp||""} onChange={e=>update("mrp",Number(e.target.value))}/></label></div>
      <label>Affiliate/product URL<input required type="url" value={form.url||""} onChange={e=>update("url",e.target.value)}/></label><label>Product image URL<input type="url" value={form.imageUrl||""} onChange={e=>update("imageUrl",e.target.value)}/></label>{form.imageUrl&&<div className="image-preview"><img src={form.imageUrl} alt="Product preview"/></div>}
      <div className="form-row"><label>Badge<input value={form.tag||""} onChange={e=>update("tag",e.target.value)}/></label><label>Coupon code<input value={form.code||""} onChange={e=>update("code",e.target.value)}/></label></div><label>Coupon conditions<input value={form.couponTerms||""} onChange={e=>update("couponTerms",e.target.value)} placeholder="Minimum spend, selected cards or users"/></label>
      <div className="form-row"><label>Expiry label<input value={form.expires||""} onChange={e=>update("expires",e.target.value)}/></label><label>Expiry date<input type="date" value={form.expiryDate||""} onChange={e=>update("expiryDate",e.target.value)}/></label></div><label>Status<select value={form.status||"published"} onChange={e=>update("status",e.target.value)}><option value="draft">Draft</option><option value="review">Review</option><option value="published">Published</option><option value="expired">Expired</option></select></label><button className="admin-primary">{form.id?"Update deal":"Save deal"}</button><p className="form-message">{message}</p>
    </form>
    <section className="catalogue"><div className="catalogue-head"><div><h2>Deal workflow</h2><span>{visible.length} records</span></div><div className="workflow-tabs">{["all","review","published","draft","expired"].map(item=><button className={filter===item?"active":""} onClick={()=>setFilter(item)} key={item}>{item}</button>)}</div></div>{visible.map(deal=><article className="admin-deal workflow-deal" key={deal.id}><div className="admin-deal-icon" style={{background:deal.color}}>{deal.imageUrl?<img src={deal.imageUrl} alt=""/>:deal.emoji}</div><div><span>{deal.platform} · {deal.category} · {deal.source}</span><h3>{deal.title}</h3><p>₹{deal.price.toLocaleString("en-IN")} <s>₹{deal.mrp.toLocaleString("en-IN")}</s> · <b className={`state-${deal.status}`}>{deal.status}</b>{deal.code&&<> · Coupon: <strong>{deal.code}</strong></>}</p><small>Checked {new Date(deal.lastCheckedAt||deal.updatedAt).toLocaleString("en-IN")}{deal.expiryDate&&` · Expires ${deal.expiryDate}`}</small></div><div className="admin-actions">{deal.status!=="published"&&<button className="approve" onClick={()=>setStatus(deal,"published")}>Publish</button>}{deal.status==="published"&&<button onClick={()=>setStatus(deal,"draft")}>Pause</button>}<button onClick={()=>setForm(deal)}>Edit</button><button className="danger" onClick={()=>remove(deal.id)}>Delete</button></div></article>)}</section></div>
  </main>;
}
