"use client";
import { useEffect, useState } from "react";
import type { Deal } from "@/lib/deal-types";

const blank = { title: "", platform: "Amazon", category: "Electronics", price: 0, mrp: 0, url: "", tag: "New deal", code: "", expires: "Limited time", emoji: "DEAL", color: "#e7f1ec", active: true, rating: 4.5, votes: 0, source: "manual" as const };

export default function AdminDashboard() {
  const [deals, setDeals] = useState<Deal[]>([]);
  const [form, setForm] = useState<Partial<Deal>>(blank);
  const [message, setMessage] = useState("Loading catalogue...");
  const [amazon, setAmazon] = useState<{ready:boolean;missing:string[]} | null>(null);
  const load = async () => { const response = await fetch("/api/admin/deals", { cache: "no-store" }); if (!response.ok) return setMessage("Sign-in failed."); setDeals(await response.json()); setMessage(""); };
  useEffect(() => { load(); fetch("/api/admin/amazon").then((r) => r.json()).then(setAmazon).catch(() => null); }, []);
  const update = (key: keyof Deal, value: string | number | boolean) => setForm((current) => ({ ...current, [key]: value }));
  const save = async (event: React.FormEvent) => { event.preventDefault(); setMessage("Saving..."); const response = await fetch("/api/admin/deals", { method: form.id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!response.ok) return setMessage((await response.json()).error || "Could not save."); setForm(blank); setMessage("Deal saved and published."); await load(); };
  const remove = async (id: number) => { if (!confirm("Delete this deal permanently?")) return; await fetch(`/api/admin/deals?id=${id}`, { method: "DELETE" }); await load(); };
  return <main className="admin-shell"><header className="admin-header"><div><a className="brand" href="/"><span className="brand-mark">%</span><span>deals<span className="brand-dot">.</span></span></a><p>Catalogue control room</p></div><div className="admin-user"><span>Admin</span><strong>tech@ads-ai.in</strong></div></header>
    <section className="admin-hero"><div><span className="eyebrow dark">DEALS OPERATIONS</span><h1>Publish a deal<br />in under a minute.</h1><p>Add, update, pause or remove offers without touching the server.</p></div><div className="admin-stats"><article><b>{deals.length}</b><span>Total deals</span></article><article><b>{deals.filter((d) => d.active).length}</b><span>Live now</span></article><article><b>{deals.filter((d) => d.platform === "Amazon").length}</b><span>Amazon</span></article></div></section>
    <section className="connector-card"><div className="amazon-badge">amazon</div><div><h2>Amazon Creators API</h2><p>{amazon?.ready ? "Connected and ready for product sync." : "Awaiting Amazon credential ID, secret, version and India partner tag."}</p></div><span className={amazon?.ready ? "status ready" : "status"}>{amazon?.ready ? "Ready" : "Setup needed"}</span></section>
    <div className="admin-grid"><form className="deal-form" onSubmit={save}><div className="form-title"><h2>{form.id ? "Edit deal" : "Add a new deal"}</h2>{form.id && <button type="button" onClick={() => setForm(blank)}>Cancel</button>}</div>
      <label>Deal title<input required value={form.title || ""} onChange={(e) => update("title", e.target.value)} placeholder="Product or offer name" /></label><div className="form-row"><label>Store<input required value={form.platform || ""} onChange={(e) => update("platform", e.target.value)} /></label><label>Category<select value={form.category} onChange={(e) => update("category", e.target.value)}>{["Mobiles","Electronics","Fashion","Home","Beauty","Travel"].map((x) => <option key={x}>{x}</option>)}</select></label></div>
      <div className="form-row"><label>Deal price (₹)<input required min="0" type="number" value={form.price || ""} onChange={(e) => update("price", Number(e.target.value))} /></label><label>MRP (₹)<input required min="1" type="number" value={form.mrp || ""} onChange={(e) => update("mrp", Number(e.target.value))} /></label></div>
      <label>Affiliate/product URL<input required type="url" value={form.url || ""} onChange={(e) => update("url", e.target.value)} placeholder="https://www.amazon.in/..." /></label><div className="form-row"><label>Badge<input value={form.tag || ""} onChange={(e) => update("tag", e.target.value)} /></label><label>Coupon code<input value={form.code || ""} onChange={(e) => update("code", e.target.value)} /></label></div><label>Expiry message<input value={form.expires || ""} onChange={(e) => update("expires", e.target.value)} /></label><label className="toggle"><input type="checkbox" checked={form.active ?? true} onChange={(e) => update("active", e.target.checked)} /> Publish on storefront</label><button className="admin-primary">{form.id ? "Update deal" : "Publish deal"}</button><p className="form-message">{message}</p></form>
      <section className="catalogue"><div className="form-title"><h2>Deal catalogue</h2><span>{deals.length} records</span></div>{deals.map((deal) => <article className="admin-deal" key={deal.id}><div className="admin-deal-icon" style={{background:deal.color}}>{deal.emoji}</div><div><span>{deal.platform} · {deal.category}</span><h3>{deal.title}</h3><p>₹{deal.price.toLocaleString("en-IN")} <s>₹{deal.mrp.toLocaleString("en-IN")}</s> · <b>{deal.active ? "Live" : "Paused"}</b></p></div><div className="admin-actions"><button onClick={() => setForm(deal)}>Edit</button><button className="danger" onClick={() => remove(deal.id)}>Delete</button></div></article>)}</section></div>
  </main>;
}
