"use client";
import { useEffect, useMemo, useState } from "react";
import type { Deal } from "@/lib/deal-types";

const blank: Partial<Deal> = { title:"", platform:"Amazon", category:"Electronics", price:0, mrp:0, url:"", imageUrl:"", tag:"New deal", code:"", couponTerms:"", expires:"Limited time", expiryDate:"", emoji:"DEAL", color:"#e7f1ec", active:true, status:"published", rating:4.5, votes:0, source:"manual" };
const sampleCsv = "title,platform,category,price,mrp,url,imageUrl,tag,code,couponTerms,expires,expiryDate,rating,votes\nProduct name,Amazon,Electronics,1499,2999,https://www.amazon.in/example,https://example.com/image.jpg,Hot deal,SAVE10,Selected users,Ends tonight,2026-08-01,4.5,100";

export default function AdminDashboard() {
  const [deals,setDeals] = useState<Deal[]>([]);
  const [form,setForm] = useState<Partial<Deal>>(blank);
  const [message,setMessage] = useState("Loading catalogue...");
  const [amazon,setAmazon] = useState<{ready:boolean;missing:string[]}|null>(null);
  const [filter,setFilter] = useState("all");
  const [csv,setCsv] = useState("");
  const today = new Date().toISOString().slice(0,10);
  const stats = useMemo(() => ({published:deals.filter(d=>d.status==="published"&&d.active).length,review:deals.filter(d=>d.status==="review").length,expired:deals.filter(d=>d.status==="expired").length,today:deals.filter(d=>d.status==="published"&&d.updatedAt?.startsWith(today)).length}),[deals,today]);
  const visible = deals.filter(d=>filter==="all"||d.status===filter);
  const load = async () => { const response=await fetch("/api/admin/deals",{cache:"no-store"}); if(!response.ok)return setMessage("Sign-in failed."); setDeals(await response.json()); setMessage(""); };
  useEffect(()=>{load();fetch("/api/admin/amazon").then(r=>r.json()).then(setAmazon).catch(()=>null)},[]);
  const update=(key:keyof Deal,value:string|number|boolean)=>setForm(current=>({...current,[key]:value}));
  const save=async(event:React.FormEvent)=>{event.preventDefault();setMessage("Saving...");const response=await fetch("/api/admin/deals",{method:form.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});if(!response.ok)return setMessage((await response.json()).error||"Could not save.");setForm(blank);setMessage("Deal saved.");await load()};
  const setStatus=async(deal:Deal,status:Deal["status"])=>{await fetch("/api/admin/deals",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...deal,status,active:status==="published"})});await load()};
  const remove=async(id:number)=>{if(!confirm("Delete this deal permanently?"))return;await fetch(`/api/admin/deals?id=${id}`,{method:"DELETE"});await load()};
  const importCsv=async()=>{if(!csv.trim())return setMessage("Paste CSV data first.");setMessage("Importing and checking duplicates...");const response=await fetch("/api/admin/import",{method:"POST",headers:{"Content-Type":"text/csv"},body:csv});const result=await response.json();if(!response.ok)return setMessage(result.error||"Import failed.");setCsv("");setMessage(`${result.imported} imported for review · ${result.skipped} duplicates skipped · ${result.errors.length} errors`);await load()};
  const readFile=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>setCsv(String(reader.result||""));reader.readAsText(file)};

  return <main className="admin-shell">
    <header className="admin-header"><div><a className="brand" href="/"><span className="brand-mark">%</span><span>deals<span className="brand-dot">.</span></span></a><p>Automation control room</p></div><div className="admin-user"><span>Admin</span><strong>tech@ads-ai.in</strong></div></header>
    <section className="admin-hero ops-hero"><div><span className="eyebrow dark">DAILY DEAL OPERATIONS</span><h1>100 smart deals.<br/>Every day.</h1><p>Import, review, publish and expire offers from one place.</p></div><div className="daily-goal"><div className="goal-ring" style={{"--progress":`${Math.min(stats.today,100)*3.6}deg`} as React.CSSProperties}><b>{stats.today}</b><span>/ 100 today</span></div></div><div className="admin-stats"><article><b>{stats.published}</b><span>Live now</span></article><article><b>{stats.review}</b><span>Needs review</span></article><article><b>{stats.expired}</b><span>Expired</span></article></div></section>
    <section className="connector-card"><div className="amazon-badge">amazon</div><div><h2>Amazon Creators API</h2><p>{amazon?.ready?"Connected and ready for scheduled sync.":"Manual and CSV imports are ready. API sync activates after Amazon credentials are added."}</p></div><span className={amazon?.ready?"status ready":"status"}>{amazon?.ready?"Ready":"Setup needed"}</span></section>
    <section className="import-card"><div><span className="import-icon">CSV</span><div><h2>Bulk deal importer</h2><p>Upload or paste a CSV. New records enter review; duplicate URLs and product titles are skipped.</p></div></div><input type="file" accept=".csv,text/csv" onChange={e=>readFile(e.target.files?.[0])}/><textarea value={csv} onChange={e=>setCsv(e.target.value)} placeholder={sampleCsv}/><div className="import-actions"><button onClick={()=>setCsv(sampleCsv)}>Load template</button><button className="admin-primary" onClick={importCsv}>Import to review queue</button></div><small>Required columns: title, platform, category, price, mrp, url. Optional: imageUrl, code, couponTerms, expiryDate, rating, votes.</small></section>
    <div className="admin-grid"><form className="deal-form" onSubmit={save}><div className="form-title"><h2>{form.id?"Edit deal":"Add one deal"}</h2>{form.id&&<button type="button" onClick={()=>setForm(blank)}>Cancel</button>}</div>
      <label>Deal title<input required value={form.title||""} onChange={e=>update("title",e.target.value)}/></label><div className="form-row"><label>Store<input required value={form.platform||""} onChange={e=>update("platform",e.target.value)}/></label><label>Category<select value={form.category} onChange={e=>update("category",e.target.value)}>{["Mobiles","Electronics","Fashion","Home","Beauty","Travel","Food","Finance"].map(x=><option key={x}>{x}</option>)}</select></label></div>
      <div className="form-row"><label>Deal price (₹)<input required min="0" type="number" value={form.price||""} onChange={e=>update("price",Number(e.target.value))}/></label><label>MRP (₹)<input required min="1" type="number" value={form.mrp||""} onChange={e=>update("mrp",Number(e.target.value))}/></label></div>
      <label>Affiliate/product URL<input required type="url" value={form.url||""} onChange={e=>update("url",e.target.value)}/></label><label>Product image URL<input type="url" value={form.imageUrl||""} onChange={e=>update("imageUrl",e.target.value)}/></label>{form.imageUrl&&<div className="image-preview"><img src={form.imageUrl} alt="Product preview"/></div>}
      <div className="form-row"><label>Badge<input value={form.tag||""} onChange={e=>update("tag",e.target.value)}/></label><label>Coupon code<input value={form.code||""} onChange={e=>update("code",e.target.value)}/></label></div><label>Coupon conditions<input value={form.couponTerms||""} onChange={e=>update("couponTerms",e.target.value)} placeholder="Minimum spend, selected cards or users"/></label>
      <div className="form-row"><label>Expiry label<input value={form.expires||""} onChange={e=>update("expires",e.target.value)}/></label><label>Expiry date<input type="date" value={form.expiryDate||""} onChange={e=>update("expiryDate",e.target.value)}/></label></div><label>Status<select value={form.status||"published"} onChange={e=>update("status",e.target.value)}><option value="draft">Draft</option><option value="review">Review</option><option value="published">Published</option><option value="expired">Expired</option></select></label><button className="admin-primary">{form.id?"Update deal":"Save deal"}</button><p className="form-message">{message}</p>
    </form>
    <section className="catalogue"><div className="catalogue-head"><div><h2>Deal workflow</h2><span>{visible.length} records</span></div><div className="workflow-tabs">{["all","review","published","draft","expired"].map(item=><button className={filter===item?"active":""} onClick={()=>setFilter(item)} key={item}>{item}</button>)}</div></div>{visible.map(deal=><article className="admin-deal workflow-deal" key={deal.id}><div className="admin-deal-icon" style={{background:deal.color}}>{deal.imageUrl?<img src={deal.imageUrl} alt=""/>:deal.emoji}</div><div><span>{deal.platform} · {deal.category} · {deal.source}</span><h3>{deal.title}</h3><p>₹{deal.price.toLocaleString("en-IN")} <s>₹{deal.mrp.toLocaleString("en-IN")}</s> · <b className={`state-${deal.status}`}>{deal.status}</b>{deal.code&&<> · Coupon: <strong>{deal.code}</strong></>}</p><small>Checked {new Date(deal.lastCheckedAt||deal.updatedAt).toLocaleString("en-IN")}{deal.expiryDate&&` · Expires ${deal.expiryDate}`}</small></div><div className="admin-actions">{deal.status!=="published"&&<button className="approve" onClick={()=>setStatus(deal,"published")}>Publish</button>}{deal.status==="published"&&<button onClick={()=>setStatus(deal,"draft")}>Pause</button>}<button onClick={()=>setForm(deal)}>Edit</button><button className="danger" onClick={()=>remove(deal.id)}>Delete</button></div></article>)}</section></div>
  </main>;
}
